### PR TITLE
Add custom encoding callback

### PR DESCRIPTION
**Pull request by orannge**
Add "_with_encoding" method, let the user decide the character encoding.

Fixes: #59.

### CODE REVIEW

**Comment by otavio** [comment]
@orannge, I'm struggling to understand why you added a new UTF locale type and couldn't use the original one?

**Comment by orannge** [comment]
@otavio, The scope of the two is different, and the windows one is inside the loop. I'll update the code after the `libarchive` library adds the `archive_entry_pathname_raw()` function, it will be more readable.

**Comment by otavio** [comment]
Can you rebase it?

**Comment by otavio** [comment]
Could you rebase it?

**Comment by otavio** [comment]
Merged in https://github.com/OSSystems/compress-tools-rs/commit/7fc6e41277e5c3d39229aa8207838545be17e7dd

**Pull request closed without merging**
