### PR TITLE
Get stat for entries

### LINKED ISSUE #75: Entry information
It would be nice to be able to get information about entries, e.g. file type or the creation time.

### PR DESCRIPTION
**Pull request by TethysSvensson**
Fixes #75.

### CODE REVIEW

**Review by otavio — APPROVED** [review]

**Comment by otavio** [comment]
Could you add an entry in `CHANGES.md`? I'd like to merge it and do a breaking release.

**Comment by TethysSvensson** [comment]
@otavio Done.

**Comment by otavio** [comment]
Merged in f654d6d.

**Comment by TethysSvensson** [comment]
@otavio Can you do a release new release with this PR included as well?

**Comment by otavio** [comment]
I just did 0.13.0 🥇

**Pull request closed without merging**
